name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'
      - run: npm install --global yarn   
      - name: Install dependencies
        run: yarn --no-audit
        # run: npm install --no-audit --no-fund --no-optional
      - name: Lint
        run: yarn link
      - name: Build
        run: yarn build-test
      - name: Test
        run: yarn test
      - name: E2E tests
        uses: cypress-io/github-action@v6
        with:
          command: yarn test:e2e
          start: yarn start-test
          wait-on: http://localhost:5000
